listen_addresses = '*'
port = 5432
max_connections = 200
password_encryption = 'scram-sha-256'
shared_buffers = '512MB'
effective_cache_size = '8GB'
maintenance_work_mem = '256MB'
work_mem = '4MB'

hot_standby = on
restore_command = '/usr/bin/pgbackrest --stanza=apps archive-get %f %p'
