listen_addresses = '*'
port = 5432
max_connections = 200
password_encryption = 'scram-sha-256'

wal_level = replica
max_wal_senders = 10
max_replication_slots = 10
hot_standby = on

archive_mode = on
archive_command = 'test ! -f /var/lib/pgsql/apps/wal-archive/%f && cp %p /var/lib/pgsql/apps/wal-archive/%f'
