Listen 10.88.0.1:18080

<VirtualHost 10.88.0.1:18080>
  ServerName code-internal.pyrosa.local

  AllowEncodedSlashes NoDecode

  ProxyPreserveHost On
  ProxyRequests Off
  ProxyAddHeaders On
  RequestHeader set X-Forwarded-Proto "https"

  <Location />
    Require ip 10.88.0.0/16
  </Location>

  RewriteEngine On
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteCond %{HTTP:Connection} upgrade [NC]
  RewriteRule /(.*) ws://127.0.0.1:8080/$1 [P,L]

  ProxyPass / http://127.0.0.1:8080/ nocanon retry=0 timeout=120
  ProxyPassReverse / http://127.0.0.1:8080/

  ErrorLog /var/log/httpd/code.pyrosa.com.do_bridge_error.log
  CustomLog /var/log/httpd/code.pyrosa.com.do_bridge_access.log combined
</VirtualHost>
