[Interface]
Address = 10.89.0.2/24
ListenPort = 51820
PrivateKey = __SECONDARY_PRIVATE_KEY__
SaveConfig = false

[Peer]
PublicKey = __PRIMARY_PUBLIC_KEY__
AllowedIPs = 10.89.0.1/32
Endpoint = 51.222.204.86:51820
PersistentKeepalive = 25
