import { type WebLocale } from "./request.js";
import { type LocalizedMailCopy } from "./mail-section-types.js";

export function getMailSectionCopy(locale: WebLocale): LocalizedMailCopy {
  return locale === "es"
    ? {
        title: "Mail",
        description:
          "Dominios de correo, buzones, aliases y quotas definidos en SimpleHost Control para el stack mail de la plataforma.",
        domainsTitle: "Dominios mail",
        mailboxesTitle: "Buzones",
        aliasesTitle: "Aliases",
        quotasTitle: "Quotas",
        formsTitle: "Edición operativa",
        formsDescription:
          "Gestiona buzones con credenciales generadas, manuales o en reset requerido. La recuperación sigue siendo solo por reset, nunca por lectura.",
        modalEditorDescription:
          "Abre un editor modal para crear un registro nuevo o ajustar el seleccionado.",
        modalDeleteDescription:
          "Confirma la eliminación del registro seleccionado antes de aplicar el cambio.",
        selectedDomainTitle: "Dominio seleccionado",
        selectedMailboxTitle: "Buzón seleccionado",
        selectedAliasTitle: "Alias seleccionado",
        selectedQuotaTitle: "Quota seleccionada",
        createLabel: "Crear",
        editLabel: "Editar",
        rotateLabel: "Rotar",
        resetLabel: "Resetear",
        deleteLabel: "Eliminar",
        actionsLabel: "Acciones",
        openEditorLabel: "Crear o editar",
        deleteSelectedLabel: "Eliminar seleccionado",
        selectedRecordLabel: "Seleccionado",
        noSelectionLabel: "Selecciona un registro primero",
        closeLabel: "Cerrar",
        domainNameLabel: "Dominio",
        mailHostLabel: "Mail host",
        webmailHostnameLabel: "Webmail host",
        dkimSelectorLabel: "Selector DKIM",
        sizeLabel: "Tamaño",
        quotaBytesLabel: "Quota",
        hasCredentialLabel: "Credencial",
        destinationsLabel: "Destinos",
        mailboxCountLabel: "Buzones",
        aliasCountLabel: "Aliases",
        runtimeTitle: "Runtime por nodo",
        runtimeDescription:
          "Estado reportado por SimpleHost Agent para postfix, dovecot, rspamd, redis y los dominios gestionados por nodo.",
        deliverabilityTitle: "Deliverability",
        deliverabilityDescription:
          "Postura derivada por dominio usando el último dns.sync aplicado y el runtime mail reportado por los nodos.",
        validationTitle: "Validaciones de producto",
        validationDescription:
          "Warnings previos al dispatch para DNS, runtime y topología mail que SimpleHostMan no puede aplicar con seguridad.",
        backupTitle: "Backup y restore",
        backupDescription:
          "Cobertura explícita de Maildir, DKIM, config runtime y estado webmail, más readiness de restore para buzón, dominio y stack mail.",
        haTitle: "Mail HA",
        haDescription:
          "Modelo activo/pasivo por dominio: el primario sirve el tráfico y el secundario solo se considera promovible cuando ya tiene artefactos y servicios listos.",
        antiSpamTitle: "Política anti-spam",
        antiSpamDescription:
          "Thresholds y controles globales de Rspamd para aceptar, etiquetar, greylistar o frenar remitentes autenticados.",
        antiSpamEditDescription:
          "Ajusta thresholds, remitentes permitidos o bloqueados, y el rate limit autenticado que SimpleHost Agent desplegará en Rspamd.",
        activityTitle: "Trazabilidad mail",
        activityDescription:
          "Conecta el dominio o recurso seleccionado con jobs recientes, auditoría y el snapshot runtime actual.",
        runtimeNodesLabel: "Nodos runtime",
        runtimeHealthyLabel: "Nodos sanos",
        backupPolicyCountLabel: "Policies backup",
        latestBackupLabel: "Último backup",
        latestBackupFailureLabel: "Último fallo backup",
        expectedPathsLabel: "Paths esperados",
        coveredPathsLabel: "Paths cubiertos",
        restoreMailboxLabel: "Restore buzón",
        restoreDomainLabel: "Restore dominio",
        restoreStackLabel: "Restore stack",
        warningCountLabel: "Warnings",
        dispatchWarningsLabel: "Bloquean dispatch",
        queuedMessagesLabel: "En cola",
        recentFailuresLabel: "Fallos recientes",
        postfixLabel: "Postfix",
        dovecotLabel: "Dovecot",
        rspamdLabel: "Rspamd",
        redisLabel: "Redis",
        webmailLabel: "Webmail",
        policyDocsLabel: "Docs de policy",
        spfLabel: "SPF",
        dkimLabel: "DKIM",
        dmarcLabel: "DMARC",
        mtaStsLabel: "MTA-STS",
        tlsRptLabel: "TLS-RPT",
        managedDomainsLabel: "Dominios gestionados",
        checkedAtLabel: "Verificado",
        failoverModeLabel: "Failover",
        manualFailoverLabel: "manual",
        dnsCutoverLabel: "Cutover DNS",
        mxBehaviorLabel: "Comportamiento MX",
        mxStableLabel: "MX sigue apuntando a mail.<dominio>",
        primaryBehaviorLabel: "Rol primario",
        primaryBehaviorValue: "SMTP/IMAP activo y firmante actual",
        standbyBehaviorLabel: "Rol secundario",
        standbyBehaviorValue: "Warm standby hasta promoción manual",
        primaryReadinessTitle: "Readiness del primario",
        standbyPromotionTitle: "Promoción del secundario",
        runtimeConfigLabel: "Config runtime",
        maildirReadinessLabel: "Maildir",
        promotionReadyLabel: "Promovible",
        promotionBlockersLabel: "Bloqueos de promoción",
        noPromotionBlockers: "No hay bloqueos reportados.",
        noStandbyConfiguredLabel: "No hay nodo secundario configurado para este dominio.",
        latestMailSyncLabel: "Último mail.sync",
        topDeferReasonLabel: "Principal defer",
        relatedJobsTitle: "Jobs relacionados",
        relatedAuditsTitle: "Auditoría relacionada",
        openJobHistoryLabel: "Abrir jobs",
        openAuditHistoryLabel: "Abrir auditoría",
        noRecentFailures: "No hay fallos recientes reportados.",
        acceptBelowLabel: "Aceptar por debajo de",
        tagAtLabel: "Etiquetar desde",
        rejectAtLabel: "Rechazar desde",
        greylistAtLabel: "Greylist desde",
        greylistDisabledLabel: "desactivado",
        senderAllowlistLabel: "Allowlist de remitentes",
        senderDenylistLabel: "Denylist de remitentes",
        senderPolicyHelp: "Usa una dirección completa o @dominio. Acepta líneas nuevas o comas.",
        noSenderPolicyEntries: "No hay entradas configuradas.",
        rateLimitLabel: "Rate limit autenticado",
        rateLimitBurstLabel: "Burst",
        rateLimitPeriodLabel: "Ventana (segundos)",
        rateLimitDisabledLabel: "desactivado",
        primaryRoleLabel: "Primario",
        secondaryRoleLabel: "Secundario",
        primaryNodeLabel: "Nodo primario",
        standbyNodeLabel: "Nodo secundario",
        saveDomainLabel: "Guardar dominio",
        deleteDomainLabel: "Eliminar dominio",
        saveMailboxLabel: "Guardar buzón",
        resetMailboxCredentialLabel: "Resetear credencial",
        deleteMailboxLabel: "Eliminar buzón",
        saveAliasLabel: "Guardar alias",
        deleteAliasLabel: "Eliminar alias",
        saveQuotaLabel: "Guardar quota",
        deleteQuotaLabel: "Eliminar quota",
        savePolicyLabel: "Guardar política",
        desiredPasswordCreateLabel: "Contraseña inicial",
        desiredPasswordUpdateLabel: "Nueva contraseña",
        credentialStrategyLabel: "Contraseña al guardar",
        credentialStrategyGenerateLabel: "Generar temporal automáticamente",
        credentialStrategyManualLabel: "Usar la contraseña escrita abajo",
        credentialStrategyMissingLabel: "Crear sin contraseña todavía",
        credentialStrategyKeepLabel: "Conservar actual",
        createMailboxDescription:
          "Crea el buzón a partir de un nombre corto dentro del dominio y decide cómo provisionar la contraseña inicial.",
        editMailboxDescription:
          "La identidad del buzón ya existe. Desde aquí puedes ajustar la quota y reemplazar la contraseña cuando quieras.",
        createMailboxPasswordHelp:
          "Si eliges generar temporal, se mostrará una sola vez. Si eliges manual, escribe la contraseña aquí antes de guardar.",
        editMailboxPasswordHelp:
          "Escribe una contraseña nueva para reemplazar la actual. Si la dejas vacía, se conserva. Usa Reset si quieres dejar el buzón en reset requerido.",
        quotaHelp: "Usa 0 para dejarlo ilimitado. Puedes elegir MB, GB o TB.",
        quotaValueLabel: "Quota Value",
        quotaUnitLabel: "Quota Unit",
        mailboxAddressHelp:
          "El nombre del buzón es la parte antes de @. Por ejemplo, en notificaciones@adudoc.com el nombre es notificaciones.",
        mailboxNameLabel: "Nombre del buzón",
        localPartLabel: "Local part",
        addressLabel: "Dirección",
        tenantSlugLabel: "Tenant",
        zoneNameLabel: "Zona",
        domainCountLabel: "Dominios",
        mailboxTotalLabel: "Buzones",
        aliasTotalLabel: "Aliases",
        quotaTotalLabel: "Quotas",
        credentialConfigured: "configurada",
        credentialMissing: "faltante",
        credentialResetRequired: "reset requerido",
        credentialRevealTitle: "Credencial de buzón",
        credentialRevealDescription:
          "Guarda esta contraseña ahora. SimpleHostMan solo la mostrará una vez.",
        credentialRevealValueLabel: "Contraseña temporal",
        credentialRevealShownOnce: "Visible solo una vez",
        credentialRevealMailboxLabel: "Buzón",
        credentialRevealGeneratedLabel: "Generada",
        credentialRevealRotatedLabel: "Rotada",
        runtimeReported: "reportado",
        runtimeUnreported: "sin reporte",
        serviceActive: "active",
        serviceInactive: "inactive",
        serviceDisabled: "disabled",
        onLabel: "on",
        offLabel: "off",
        observabilityReady: "listo",
        observabilityWarning: "parcial",
        observabilityMissing: "faltante",
        observabilityUnreported: "sin reporte",
        validationAffectsDispatchLabel: "Afecta dispatch",
        validationAdvisoryLabel: "Warning operativo",
        openBackupsViewLabel: "Abrir backups",
        noExpectedBackupPaths: "Aún no hay paths runtime confirmados para este artefacto.",
        noMailDomains: "No hay dominios mail.",
        noMailboxes: "No hay buzones.",
        noAliases: "No hay aliases.",
        noQuotas: "No hay quotas.",
        noValidationWarnings: "No hay warnings de validación para este dominio.",
        noRuntimeNodes: "Ningún nodo relevante ha reportado runtime mail todavía."
      }
    : {
        title: "Mail",
        description:
          "Mail domains, mailboxes, aliases and quotas defined in SimpleHost Control for the platform mail stack.",
        domainsTitle: "Mail domains",
        mailboxesTitle: "Mailboxes",
        aliasesTitle: "Aliases",
        quotasTitle: "Quotas",
        formsTitle: "Operator editing",
        formsDescription:
          "Manage mailboxes with generated, manual, or reset-required credentials. Recovery remains reset-only and never readable.",
        modalEditorDescription:
          "Open a modal editor to create a new record or adjust the selected one.",
        modalDeleteDescription:
          "Confirm the selected record before applying a destructive delete.",
        selectedDomainTitle: "Selected domain",
        selectedMailboxTitle: "Selected mailbox",
        selectedAliasTitle: "Selected alias",
        selectedQuotaTitle: "Selected quota",
        createLabel: "Create",
        editLabel: "Edit",
        rotateLabel: "Rotate",
        resetLabel: "Reset",
        deleteLabel: "Delete",
        actionsLabel: "Actions",
        openEditorLabel: "Create or edit",
        deleteSelectedLabel: "Delete selected",
        selectedRecordLabel: "Selected",
        noSelectionLabel: "Select a record first",
        closeLabel: "Close",
        domainNameLabel: "Domain",
        mailHostLabel: "Mail host",
        webmailHostnameLabel: "Webmail host",
        dkimSelectorLabel: "DKIM selector",
        sizeLabel: "Size",
        quotaBytesLabel: "Quota",
        hasCredentialLabel: "Credential",
        destinationsLabel: "Destinations",
        mailboxCountLabel: "Mailboxes",
        aliasCountLabel: "Aliases",
        runtimeTitle: "Node runtime",
        runtimeDescription:
          "Per-node mail service status reported by SimpleHost Agent for postfix, dovecot, rspamd, redis and managed domains.",
        deliverabilityTitle: "Deliverability",
        deliverabilityDescription:
          "Per-domain posture derived from the latest applied dns.sync payload plus node-reported mail runtime.",
        validationTitle: "Product validations",
        validationDescription:
          "Pre-dispatch warnings for DNS, runtime, and mail topology states that SimpleHostMan cannot safely apply.",
        backupTitle: "Backup and restore",
        backupDescription:
          "Explicit Maildir, DKIM, runtime config, and webmail-state coverage, plus restore readiness for mailbox, domain, and the full mail stack.",
        haTitle: "Mail HA",
        haDescription:
          "Per-domain active/passive model: the primary serves traffic and the secondary is only treated as promotable when artifacts and services are ready.",
        antiSpamTitle: "Anti-spam policy",
        antiSpamDescription:
          "Explicit Rspamd thresholds and global controls for accept, tag, greylist, sender lists, and authenticated sender throttling.",
        antiSpamEditDescription:
          "Adjust thresholds, trusted or blocked senders, and the authenticated sender rate limit that SimpleHost Agent deploys into Rspamd.",
        activityTitle: "Mail tracing",
        activityDescription:
          "Connect the selected mail resource to recent jobs, audit history, and the current runtime snapshot.",
        runtimeNodesLabel: "Runtime nodes",
        runtimeHealthyLabel: "Healthy nodes",
        backupPolicyCountLabel: "Backup policies",
        latestBackupLabel: "Latest backup",
        latestBackupFailureLabel: "Latest backup failure",
        expectedPathsLabel: "Expected paths",
        coveredPathsLabel: "Covered paths",
        restoreMailboxLabel: "Mailbox restore",
        restoreDomainLabel: "Domain restore",
        restoreStackLabel: "Mail stack restore",
        warningCountLabel: "Warnings",
        dispatchWarningsLabel: "Block dispatch",
        queuedMessagesLabel: "Queued",
        recentFailuresLabel: "Recent failures",
        postfixLabel: "Postfix",
        dovecotLabel: "Dovecot",
        rspamdLabel: "Rspamd",
        redisLabel: "Redis",
        webmailLabel: "Webmail",
        policyDocsLabel: "Policy docs",
        spfLabel: "SPF",
        dkimLabel: "DKIM",
        dmarcLabel: "DMARC",
        mtaStsLabel: "MTA-STS",
        tlsRptLabel: "TLS-RPT",
        managedDomainsLabel: "Managed domains",
        checkedAtLabel: "Checked",
        failoverModeLabel: "Failover",
        manualFailoverLabel: "manual",
        dnsCutoverLabel: "DNS cutover",
        mxBehaviorLabel: "MX behavior",
        mxStableLabel: "MX keeps pointing at mail.<domain>",
        primaryBehaviorLabel: "Primary role",
        primaryBehaviorValue: "Active SMTP/IMAP ingress and current signer",
        standbyBehaviorLabel: "Standby role",
        standbyBehaviorValue: "Warm standby until manual promotion",
        primaryReadinessTitle: "Primary readiness",
        standbyPromotionTitle: "Standby promotion",
        runtimeConfigLabel: "Runtime config",
        maildirReadinessLabel: "Maildir",
        promotionReadyLabel: "Promotable",
        promotionBlockersLabel: "Promotion blockers",
        noPromotionBlockers: "No blockers reported.",
        noStandbyConfiguredLabel: "No standby node is configured for this domain.",
        latestMailSyncLabel: "Latest mail.sync",
        topDeferReasonLabel: "Top defer",
        relatedJobsTitle: "Related jobs",
        relatedAuditsTitle: "Related audit",
        openJobHistoryLabel: "Open jobs",
        openAuditHistoryLabel: "Open audit",
        noRecentFailures: "No recent delivery failures reported.",
        acceptBelowLabel: "Accept below",
        tagAtLabel: "Tag at",
        rejectAtLabel: "Reject at",
        greylistAtLabel: "Greylist at",
        greylistDisabledLabel: "disabled",
        senderAllowlistLabel: "Sender allowlist",
        senderDenylistLabel: "Sender denylist",
        senderPolicyHelp: "Use a full sender address or @domain. New lines and commas are both accepted.",
        noSenderPolicyEntries: "No entries configured.",
        rateLimitLabel: "Authenticated sender rate limit",
        rateLimitBurstLabel: "Burst",
        rateLimitPeriodLabel: "Window (seconds)",
        rateLimitDisabledLabel: "disabled",
        primaryRoleLabel: "Primary",
        secondaryRoleLabel: "Secondary",
        primaryNodeLabel: "Primary node",
        standbyNodeLabel: "Standby node",
        saveDomainLabel: "Save domain",
        deleteDomainLabel: "Delete domain",
        saveMailboxLabel: "Save mailbox",
        resetMailboxCredentialLabel: "Reset credential",
        deleteMailboxLabel: "Delete mailbox",
        saveAliasLabel: "Save alias",
        deleteAliasLabel: "Delete alias",
        saveQuotaLabel: "Save quota",
        deleteQuotaLabel: "Delete quota",
        savePolicyLabel: "Save policy",
        desiredPasswordCreateLabel: "Initial password",
        desiredPasswordUpdateLabel: "New password",
        credentialStrategyLabel: "Password on save",
        credentialStrategyGenerateLabel: "Generate a temporary password",
        credentialStrategyManualLabel: "Use the password typed below",
        credentialStrategyMissingLabel: "Create without a password yet",
        credentialStrategyKeepLabel: "Keep current",
        createMailboxDescription:
          "Create the mailbox from a short mailbox name inside the selected domain and decide how to provision the initial password.",
        editMailboxDescription:
          "The mailbox identity already exists. Use this editor to adjust quota and replace the password whenever needed.",
        createMailboxPasswordHelp:
          "Generated passwords are shown once. If you choose manual, type it here before saving.",
        editMailboxPasswordHelp:
          "Type a new password to replace the current one. Leave it blank to keep the existing secret. Use Reset if you want the mailbox to move back to reset-required.",
        quotaHelp: "Use 0 for unlimited. You can choose MB, GB, or TB.",
        quotaValueLabel: "Quota Value",
        quotaUnitLabel: "Quota Unit",
        mailboxAddressHelp:
          "Mailbox name means the part before @. For example, in notifications@adudoc.com the mailbox name is notifications.",
        mailboxNameLabel: "Mailbox name",
        localPartLabel: "Local part",
        addressLabel: "Address",
        tenantSlugLabel: "Tenant",
        zoneNameLabel: "Zone",
        domainCountLabel: "Domains",
        mailboxTotalLabel: "Mailboxes",
        aliasTotalLabel: "Aliases",
        quotaTotalLabel: "Quotas",
        credentialConfigured: "configured",
        credentialMissing: "missing",
        credentialResetRequired: "reset required",
        credentialRevealTitle: "Mailbox credential",
        credentialRevealDescription:
          "Save this password now. SimpleHostMan will only show it once.",
        credentialRevealValueLabel: "Temporary password",
        credentialRevealShownOnce: "Shown only once",
        credentialRevealMailboxLabel: "Mailbox",
        credentialRevealGeneratedLabel: "Generated",
        credentialRevealRotatedLabel: "Rotated",
        runtimeReported: "reported",
        runtimeUnreported: "unreported",
        serviceActive: "active",
        serviceInactive: "inactive",
        serviceDisabled: "disabled",
        onLabel: "on",
        offLabel: "off",
        observabilityReady: "ready",
        observabilityWarning: "partial",
        observabilityMissing: "missing",
        observabilityUnreported: "unreported",
        validationAffectsDispatchLabel: "Affects dispatch",
        validationAdvisoryLabel: "Operational warning",
        openBackupsViewLabel: "Open backups",
        noExpectedBackupPaths: "No confirmed runtime paths are available for this artifact yet.",
        noMailDomains: "No mail domains.",
        noMailboxes: "No mailboxes.",
        noAliases: "No aliases.",
        noQuotas: "No quotas.",
        noValidationWarnings: "No validation warnings for this domain.",
        noRuntimeNodes: "No relevant nodes have reported mail runtime yet."
      };
}
