import { type WebLocale } from "./request.js";
import { type WebCopyDictionary } from "./web-copy-types.js";

export const operationsCopyByLocale = {
  en: {
    dashboardHeading: "Control plane",
    dashboardSubheading:
      "Operate nodes, jobs, backups, and platform resources from a single control surface.",
    overviewDescription: "Live platform counts plus the main control-plane actions.",
    actionsRunReconciliation: "Run reconciliation",
    actionsImportInventory: "Bootstrap YAML import",
    actionsDownloadYaml: "Download resource YAML",
    actionDispatchDnsSync: "Dispatch dns.sync",
    actionFullReconcile: "Full reconcile",
    actionDispatchProxyRender: "Dispatch proxy.render",
    actionDispatchDatabaseReconcile: "Dispatch database reconcile",
    actionPlanDescription:
      "Compare the platform resource catalog against the last successful apply and dispatch missing work.",
    actionImportDescription:
      "Use the transitional YAML import path to seed or recover the PostgreSQL resource catalog.",
    actionExportDescription:
      "Export the current resource catalog for audit, review, or disaster recovery.",
    overviewTitle: "Operations overview",
    managedNodes: "Managed nodes",
    pendingJobs: "Pending jobs",
    failedJobs: "Failed jobs",
    resourcesWithDrift: "Resources with drift",
    backupPolicies: "Backup policies",
    generatedAt: "Generated",
    usersAndScope: "Users and scope",
    inventoryImport: "Inventory import",
    latestReconciliation: "Latest reconciliation",
    auditTrailTitle: "Recent audit",
    auditTrailDescription: "Recent control-plane mutations and runtime events.",
    payloadTitle: "Payload and result",
    previewTitle: "Dispatch preview",
    impactPreviewTitle: "Impact preview",
    queuedWorkTitle: "Queued work preview",
    queuedWorkDescription: "Expected jobs and target nodes for the selected action.",
    dangerZoneTitle: "Danger zone",
    linkedOperationsTitle: "Linked operations",
    operationalSignalsTitle: "Operational signals",
    failureFocusTitle: "Failure focus",
    failureFocusDescription: "Most recent failed operations in the current workspace.",
    auditSignalsTitle: "Audit signals",
    auditSignalsDescription: "Most active event types in the current slice.",
    auditActorsTitle: "Audit actors",
    auditActorsDescription: "Recent actors and touched entities in the current slice.",
    desiredAppliedTitle: "Desired vs last applied",
    desiredAppliedDescription:
      "Compare the current desired definition with the latest successful job payload.",
    plannedChangesTitle: "Planned changes",
    plannedChangesDescription:
      "Preview what the selected action is expected to touch before dispatching or deleting.",
    effectiveStateTitle: "Effective state",
    effectiveStateDescription:
      "Current operational posture, most recent outcomes and related control-plane scope.",
    fieldDeltaTitle: "Field deltas",
    fieldDeltaDescription:
      "Desired fields that differ from the last applied payload or still lack a confirmed runtime value.",
    comparisonFieldLabel: "Field",
    comparisonDesiredLabel: "Desired",
    comparisonAppliedLabel: "Last applied",
    comparisonStatusLabel: "Status",
    comparisonMatchLabel: "match",
    comparisonChangedLabel: "changed",
    comparisonUnknownLabel: "unknown",
    noFieldDeltas: "No field-level deltas detected.",
    jobStatusesTitle: "Job status mix",
    jobStatusesDescription: "Current distribution of queued, applied and failed work.",
    jobResourceHotspotsTitle: "Resource hotspots",
    jobResourceHotspotsDescription: "Resources accumulating the most recent job activity.",
    auditEntitiesTitle: "Audit entities",
    auditEntitiesDescription: "Entities touched most often in the current audit slice.",
    backupCoverageTitle: "Coverage summary",
    backupCoverageDescription: "Policy reach, last known outcomes and tenant scope for backups.",
    backupCoverageByTenantTitle: "Coverage by tenant",
    backupCoverageByTenantDescription:
      "Tenants currently protected by policy scope and their covered resource counts.",
    backupPolicySignalsTitle: "Policy signals",
    backupPolicySignalsDescription: "Policies with the busiest recent run history.",
    backupTargetPostureTitle: "Backup target posture",
    backupTargetPostureDescription:
      "Current target-node health, selected policy spread and latest known outcomes.",
    backupRunSignalsTitle: "Backup run signals",
    backupRunSignalsDescription: "Recent backup mix by node and outcome.",
    backupNodesTitle: "Backup activity by node",
    backupNodesDescription: "Nodes receiving the most recent backup activity.",
    jobNodesTitle: "Job activity by node",
    jobNodesDescription: "Recent dispatch concentration and latest status by node.",
    jobKindsTitle: "Job kind mix",
    jobKindsDescription: "Recent workload mix and most active job kinds.",
    driftStatusesTitle: "Drift by status",
    driftStatusesDescription: "Current drift split by status for the selected slice.",
    driftNodesTitle: "Drift by node",
    driftNodesDescription: "Nodes accumulating the most unresolved drift.",
    driftKindsTitle: "Drift by kind",
    driftKindsDescription: "Which resource families are currently drifting the most.",
    activeFiltersTitle: "Active filters",
    activeFiltersDescription: "The current diagnostic slice applied to this workspace.",
    clearFiltersLabel: "Clear filters",
    applyFiltersLabel: "Apply filters",
    filterWorkspaceTitle: "Refine workspace",
    filterWorkspaceDescription:
      "Use structured filters to narrow the current operational slice before opening a specific record.",
    filterActorLabel: "Actor",
    filterStatusLabel: "Status",
    filterKindLabel: "Kind",
    filterNodeLabel: "Node",
    filterResourceLabel: "Resource",
    filterPolicyLabel: "Policy",
    filterTenantLabel: "Tenant",
    filterEventLabel: "Event type",
    filterEntityLabel: "Entity",
    relatedJobsTitle: "Related jobs",
    relatedDriftTitle: "Related drift",
    relatedResourcesTitle: "Related resources",
    relatedResourcesDescription:
      "Jump to the records, nodes and policies linked to the selected workspace item.",
    latestCompleted: "Completed",
    latestFailureLabel: "Latest failure",
    latestSuccessLabel: "Latest success",
    desiredHash: "Desired hash",
    latestHash: "Applied hash",
    dispatchRecommended: "Dispatch recommended",
    linkedResource: "Linked resource",
    affectedResourcesLabel: "Affected resources",
    targetedNodesLabel: "Targeted nodes",
    openDesiredState: "Open desired-state record",
    storageLocationLabel: "Storage location",
    resourceSelectorsLabel: "Resource selectors",
    healthyNodes: "Healthy nodes",
    staleNodes: "Stale nodes",
    nodesWithPendingJobs: "Nodes with pending jobs",
    nodesWithFailures: "Nodes with failures",
    driftPending: "Pending drift",
    driftOutOfSync: "Out-of-sync drift",
    driftMissingSecrets: "Missing secrets",
    recentQueuedJobs: "Queued jobs",
    recentAppliedJobs: "Applied jobs",
    recentFailedJobs: "Failed jobs",
    succeededBackups: "Succeeded backups",
    failedBackups: "Failed backups",
    runningBackups: "Running backups",
    policyCoverage: "Policy coverage",
    transitionalBootstrapNote:
      "Transitional only. Keep operational edits in PostgreSQL desired state.",
    dailyOperationsSourceNote:
      "Use these product forms for day-to-day changes. YAML remains a bootstrap and disaster-recovery path only.",
    openJobHistory: "Open job history",
    openAuditHistory: "Open audit",
    openDriftView: "Open drift view",
    viewApacheVhost: "View Apache vhost",
    openBackupsView: "Open backups view",
    openNodeHealth: "Open node health",
    nodeDiagnosticsTitle: "Node diagnostics",
    nodeDiagnosticsDescription:
      "Inspect drift, recent jobs and routing scope for the selected node.",
    driftDiagnosticsTitle: "Drift diagnostics",
    driftDiagnosticsDescription:
      "Inspect the selected drift record, linked resource specification and dispatch guidance.",
    bootstrapInventoryTitle: "Catalog import/export",
    bootstrapInventoryDescription:
      "Export the PostgreSQL resource catalog as YAML for review or recovery. Use YAML import only for controlled seed or disaster-recovery flows.",
    globalRoles: "Global roles",
    tenantMemberships: "Tenant memberships",
    yesLabel: "yes",
    noLabel: "no",
    none: "none",
    latestImport: "Latest import",
    latestExport: "Latest export",
    never: "never",
    noRelatedRecords: "No related records.",
    latestImportCounts: "Nodes {nodes}, zones {zones}, apps {apps}, databases {databases}",
    noReconciliationRun: "No reconciliation run recorded yet.",
    reconciliationVersion: "Version {version}",
    reconciliationSummary: "Generated {generated}, skipped {skipped}, missing secrets {missing}",
    backupRunTitle: "Latest backup run",
    backupRunDescription:
      "Inspect the last known run and policy context for the selected backup policy.",
    backupPolicyContextTitle: "Policy context",
    backupPolicyContextDescription: "Policy metadata and linked operational scope.",
    nodeHealthTitle: "Node health",
    nodeHealthDescription: "Health, version, pending jobs and latest result by node.",
    resourceDriftTitle: "Resource drift",
    resourceDriftDescription: "Current reconciliation view across DNS, proxy and databases.",
    jobHistoryTitle: "Jobs",
    jobHistoryDescription: "Recent control-plane dispatches, outcomes and related execution status.",
    packagesTitle: "Packages",
    packagesDescription:
      "Installed RPM inventory plus repository and URL-based package rollout across managed nodes.",
    backupsTitle: "Backups",
    backupsDescription: "Latest runs and current backup policy coverage.",
    packagesInventoryTitle: "Installed packages",
    packagesInventoryDescription:
      "Review the latest collected RPM inventory snapshot across managed nodes.",
    selectedPackageTitle: "Selected package",
    selectedPackageDescription:
      "Inspect the latest collected metadata for the focused package record.",
    packageActionsTitle: "Package actions",
    packageActionsDescription:
      "Refresh inventory or dispatch package installs against the selected node set.",
    packageRefreshTitle: "Refresh inventory",
    packageRefreshDescription:
      "Collect a fresh RPM inventory snapshot from the selected nodes.",
    packageInstallRepoTitle: "Install from repo",
    packageInstallRepoDescription:
      "Install one or more package names from the configured repositories on the selected nodes.",
    packageInstallUrlTitle: "Install from RPM URL",
    packageInstallUrlDescription:
      "Install a package directly from an absolute RPM URL, optionally validating its SHA-256.",
    packageColPackage: "Package",
    packageColVersion: "Version",
    packageColArch: "Arch",
    packageColNode: "Node",
    packageColHostname: "Hostname",
    packageColInstalled: "Installed",
    packageColCollected: "Collected",
    packageNamesLabel: "Package names",
    packageRpmUrlLabel: "RPM URL",
    packageExpectedSha256Label: "Expected SHA-256",
    packageAllowReinstallLabel: "Allow reinstall",
    packageSourceLabel: "Source",
    packageNevraLabel: "NEVRA",
    filterPackageLabel: "Package",
    refreshInventoryLabel: "Refresh inventory",
    installFromRepoLabel: "Install from repo",
    installFromUrlLabel: "Install from URL",
    packageNamesPlaceholder: "e.g. htop jq git",
    packageRpmUrlPlaceholder:
      "https://github.com/coder/code-server/releases/download/v4.115.0/code-server-4.115.0-amd64.rpm",
    noPackages: "No package records."
  },
  es: {
    dashboardHeading: "Plano de control",
    dashboardSubheading:
      "Opera nodos, jobs, backups y recursos de plataforma desde una sola consola.",
    overviewDescription:
      "Conteos vivos de la plataforma y las acciones principales del control plane.",
    actionsRunReconciliation: "Ejecutar reconciliación",
    actionsImportInventory: "Importar YAML bootstrap",
    actionsDownloadYaml: "Descargar YAML de recursos",
    actionDispatchDnsSync: "Despachar dns.sync",
    actionFullReconcile: "Reconciliación completa",
    actionDispatchProxyRender: "Despachar proxy.render",
    actionDispatchDatabaseReconcile: "Despachar reconcile de base de datos",
    actionPlanDescription:
      "Compara el catálogo de recursos de plataforma con la última aplicación exitosa y despacha el trabajo faltante.",
    actionImportDescription:
      "Usa la ruta YAML transicional para sembrar o recuperar el catálogo de recursos en PostgreSQL.",
    actionExportDescription:
      "Exporta el catálogo actual de recursos para auditoría, revisión o recuperación.",
    overviewTitle: "Resumen operativo",
    managedNodes: "Nodos gestionados",
    pendingJobs: "Jobs pendientes",
    failedJobs: "Jobs fallidos",
    resourcesWithDrift: "Recursos con drift",
    backupPolicies: "Políticas de backup",
    generatedAt: "Generado",
    usersAndScope: "Usuarios y alcance",
    inventoryImport: "Importación de inventario",
    latestReconciliation: "Última reconciliación",
    auditTrailTitle: "Auditoría reciente",
    auditTrailDescription: "Mutaciones recientes del control plane y eventos de runtime.",
    payloadTitle: "Payload y resultado",
    previewTitle: "Vista previa del despacho",
    impactPreviewTitle: "Vista previa de impacto",
    queuedWorkTitle: "Vista previa del trabajo en cola",
    queuedWorkDescription: "Jobs esperados y nodos objetivo para la acción seleccionada.",
    dangerZoneTitle: "Zona sensible",
    linkedOperationsTitle: "Operaciones vinculadas",
    operationalSignalsTitle: "Señales operativas",
    failureFocusTitle: "Foco de fallos",
    failureFocusDescription:
      "Operaciones fallidas más recientes dentro del workspace actual.",
    auditSignalsTitle: "Señales de auditoría",
    auditSignalsDescription: "Tipos de evento más activos dentro del corte actual.",
    auditActorsTitle: "Actores de auditoría",
    auditActorsDescription: "Actores recientes y entidades tocadas dentro del corte actual.",
    desiredAppliedTitle: "Deseado vs último aplicado",
    desiredAppliedDescription:
      "Compara la definición deseada actual con el payload del último job exitoso.",
    plannedChangesTitle: "Cambios previstos",
    plannedChangesDescription:
      "Vista previa de lo que la acción seleccionada debería tocar antes de despachar o borrar.",
    effectiveStateTitle: "Estado efectivo",
    effectiveStateDescription:
      "Postura operativa actual, últimos resultados y alcance relacionado del control plane.",
    fieldDeltaTitle: "Deltas por campo",
    fieldDeltaDescription:
      "Campos deseados que difieren del último payload aplicado o que todavía no tienen un valor de runtime confirmado.",
    comparisonFieldLabel: "Campo",
    comparisonDesiredLabel: "Deseado",
    comparisonAppliedLabel: "Último aplicado",
    comparisonStatusLabel: "Estado",
    comparisonMatchLabel: "coincide",
    comparisonChangedLabel: "cambió",
    comparisonUnknownLabel: "sin dato",
    noFieldDeltas: "No se detectaron deltas por campo.",
    jobStatusesTitle: "Mezcla de estados de jobs",
    jobStatusesDescription:
      "Distribución actual de trabajo en cola, aplicado y fallido.",
    jobResourceHotspotsTitle: "Recursos más activos",
    jobResourceHotspotsDescription:
      "Recursos que acumulan más actividad reciente de jobs.",
    auditEntitiesTitle: "Entidades de auditoría",
    auditEntitiesDescription:
      "Entidades tocadas con más frecuencia dentro del corte actual.",
    backupCoverageTitle: "Resumen de cobertura",
    backupCoverageDescription:
      "Alcance de políticas, últimos resultados conocidos y alcance por tenant para backups.",
    backupCoverageByTenantTitle: "Cobertura por tenant",
    backupCoverageByTenantDescription:
      "Tenants protegidos actualmente por las políticas y sus recursos cubiertos.",
    backupPolicySignalsTitle: "Señales por política",
    backupPolicySignalsDescription:
      "Políticas con más actividad reciente de ejecuciones.",
    backupTargetPostureTitle: "Postura del destino de backup",
    backupTargetPostureDescription:
      "Salud actual del nodo destino, alcance de la política seleccionada y últimos resultados conocidos.",
    backupRunSignalsTitle: "Señales de ejecuciones de backup",
    backupRunSignalsDescription: "Mezcla reciente de backups por nodo y resultado.",
    backupNodesTitle: "Actividad de backups por nodo",
    backupNodesDescription: "Nodos que reciben más actividad reciente de backup.",
    jobNodesTitle: "Actividad de jobs por nodo",
    jobNodesDescription: "Concentración reciente de despachos y último estado por nodo.",
    jobKindsTitle: "Mezcla de tipos de job",
    jobKindsDescription: "Carga reciente y tipos de job más activos.",
    driftStatusesTitle: "Drift por estado",
    driftStatusesDescription:
      "Reparto actual del drift por estado dentro del corte seleccionado.",
    driftNodesTitle: "Drift por nodo",
    driftNodesDescription: "Nodos que acumulan más drift sin resolver.",
    driftKindsTitle: "Drift por tipo",
    driftKindsDescription: "Familias de recursos con mayor drift actual.",
    activeFiltersTitle: "Filtros activos",
    activeFiltersDescription: "Corte diagnóstico actual aplicado a este workspace.",
    clearFiltersLabel: "Limpiar filtros",
    applyFiltersLabel: "Aplicar filtros",
    filterWorkspaceTitle: "Refinar workspace",
    filterWorkspaceDescription:
      "Usa filtros estructurados para acotar el corte operativo actual antes de abrir un registro específico.",
    filterActorLabel: "Actor",
    filterStatusLabel: "Estado",
    filterKindLabel: "Tipo",
    filterNodeLabel: "Nodo",
    filterResourceLabel: "Recurso",
    filterPolicyLabel: "Política",
    filterTenantLabel: "Tenant",
    filterEventLabel: "Tipo de evento",
    filterEntityLabel: "Entidad",
    relatedJobsTitle: "Jobs relacionados",
    relatedDriftTitle: "Drift relacionado",
    relatedResourcesTitle: "Recursos relacionados",
    relatedResourcesDescription:
      "Salta a los registros, nodos y políticas vinculadas al elemento seleccionado.",
    latestCompleted: "Completado",
    latestFailureLabel: "Último fallo",
    latestSuccessLabel: "Último éxito",
    desiredHash: "Hash deseado",
    latestHash: "Hash aplicado",
    dispatchRecommended: "Despacho recomendado",
    linkedResource: "Recurso vinculado",
    affectedResourcesLabel: "Recursos afectados",
    targetedNodesLabel: "Nodos objetivo",
    openDesiredState: "Abrir recurso en estado deseado",
    storageLocationLabel: "Ubicación de almacenamiento",
    resourceSelectorsLabel: "Selectores de recursos",
    healthyNodes: "Nodos saludables",
    staleNodes: "Nodos sin señal reciente",
    nodesWithPendingJobs: "Nodos con jobs pendientes",
    nodesWithFailures: "Nodos con fallos",
    driftPending: "Drift pendiente",
    driftOutOfSync: "Drift fuera de sincronía",
    driftMissingSecrets: "Secretos faltantes",
    recentQueuedJobs: "Jobs en cola",
    recentAppliedJobs: "Jobs aplicados",
    recentFailedJobs: "Jobs fallidos",
    succeededBackups: "Backups exitosos",
    failedBackups: "Backups fallidos",
    runningBackups: "Backups ejecutándose",
    policyCoverage: "Cobertura de políticas",
    transitionalBootstrapNote:
      "Solo transicional. Mantén las ediciones operativas en PostgreSQL como estado deseado.",
    dailyOperationsSourceNote:
      "Usa estos formularios del producto para los cambios del día a día. El YAML queda solo para bootstrap y disaster recovery.",
    openJobHistory: "Abrir historial de jobs",
    openAuditHistory: "Abrir auditoría",
    openDriftView: "Abrir vista de drift",
    viewApacheVhost: "Ver Apache vhost",
    openBackupsView: "Abrir vista de backups",
    openNodeHealth: "Abrir salud del nodo",
    nodeDiagnosticsTitle: "Diagnóstico del nodo",
    nodeDiagnosticsDescription:
      "Inspecciona drift, jobs recientes y alcance operativo del nodo seleccionado.",
    driftDiagnosticsTitle: "Diagnóstico de drift",
    driftDiagnosticsDescription:
      "Inspecciona el registro de drift seleccionado, su especificación vinculada y la guía de despacho.",
    bootstrapInventoryTitle: "Importación/exportación del catálogo",
    bootstrapInventoryDescription:
      "Exporta el catálogo de recursos en PostgreSQL como YAML para revisión o recovery. Usa la importación YAML solo para seed controlado o disaster recovery.",
    globalRoles: "Roles globales",
    tenantMemberships: "Membresías por tenant",
    yesLabel: "sí",
    noLabel: "no",
    none: "ninguna",
    latestImport: "Última importación",
    latestExport: "Última exportación",
    never: "nunca",
    noRelatedRecords: "No hay registros relacionados.",
    latestImportCounts: "Nodos {nodes}, zonas {zones}, apps {apps}, bases de datos {databases}",
    noReconciliationRun: "Todavía no hay una reconciliación registrada.",
    reconciliationVersion: "Versión {version}",
    reconciliationSummary: "Generados {generated}, omitidos {skipped}, secretos faltantes {missing}",
    backupRunTitle: "Última ejecución de backup",
    backupRunDescription:
      "Inspecciona la última ejecución conocida y el contexto de la política seleccionada.",
    backupPolicyContextTitle: "Contexto de la política",
    backupPolicyContextDescription: "Metadatos de la política y alcance operativo vinculado.",
    nodeHealthTitle: "Salud de nodos",
    nodeHealthDescription:
      "Estado, versión, jobs pendientes y último resultado por nodo.",
    resourceDriftTitle: "Drift de recursos",
    resourceDriftDescription:
      "Vista actual de reconciliación sobre DNS, proxy y bases de datos.",
    jobHistoryTitle: "Jobs",
    jobHistoryDescription:
      "Despachos recientes del control plane, resultados y estado de ejecución relacionado.",
    packagesTitle: "Paquetes",
    packagesDescription:
      "Inventario RPM instalado más despliegue de paquetes desde repositorios o URL sobre nodos gestionados.",
    backupsTitle: "Backups",
    backupsDescription: "Últimas ejecuciones y cobertura actual de políticas.",
    packagesInventoryTitle: "Paquetes instalados",
    packagesInventoryDescription:
      "Revisa el último snapshot recolectado del inventario RPM en los nodos gestionados.",
    selectedPackageTitle: "Paquete seleccionado",
    selectedPackageDescription:
      "Inspecciona los metadatos más recientes recolectados para el paquete enfocado.",
    packageActionsTitle: "Acciones de paquetes",
    packageActionsDescription:
      "Refresca inventario o despacha instalaciones de paquetes sobre el conjunto de nodos seleccionado.",
    packageRefreshTitle: "Refrescar inventario",
    packageRefreshDescription:
      "Recolecta un snapshot fresco del inventario RPM desde los nodos seleccionados.",
    packageInstallRepoTitle: "Instalar desde repo",
    packageInstallRepoDescription:
      "Instala uno o más nombres de paquetes desde los repositorios configurados en los nodos seleccionados.",
    packageInstallUrlTitle: "Instalar desde URL RPM",
    packageInstallUrlDescription:
      "Instala un paquete directamente desde una URL RPM absoluta, validando opcionalmente su SHA-256.",
    packageColPackage: "Paquete",
    packageColVersion: "Versión",
    packageColArch: "Arquitectura",
    packageColNode: "Nodo",
    packageColHostname: "Hostname",
    packageColInstalled: "Instalado",
    packageColCollected: "Recolectado",
    packageNamesLabel: "Nombres de paquetes",
    packageRpmUrlLabel: "URL RPM",
    packageExpectedSha256Label: "SHA-256 esperado",
    packageAllowReinstallLabel: "Permitir reinstalar",
    packageSourceLabel: "Origen",
    packageNevraLabel: "NEVRA",
    filterPackageLabel: "Paquete",
    refreshInventoryLabel: "Refrescar inventario",
    installFromRepoLabel: "Instalar desde repo",
    installFromUrlLabel: "Instalar desde URL",
    packageNamesPlaceholder: "ej. htop jq git",
    packageRpmUrlPlaceholder:
      "https://github.com/coder/code-server/releases/download/v4.115.0/code-server-4.115.0-amd64.rpm",
    noPackages: "No hay registros de paquetes."
  }
} satisfies Record<WebLocale, WebCopyDictionary>;
