setuid=pdns
setgid=pdns

local-address=0.0.0.0,::
local-port=53
version-string=anonymous

launch=lmdb
lmdb-filename=/var/lib/pdns/lmdb/pdns.lmdb

primary=yes
secondary=no

api=yes
api-key=__PDNS_API_KEY__
webserver=yes
webserver-address=127.0.0.1
webserver-port=8081
webserver-allow-from=127.0.0.1,10.89.0.0/24

allow-axfr-ips=10.89.0.2
allow-dnsupdate-from=127.0.0.1,10.89.0.0/24
default-api-rectify=yes
default-soa-edit=INCEPTION-INCREMENT
default-soa-edit-signed=INCEPTION-INCREMENT
